# The start symbol is START.

# These two rules are required; choose their weights carefully!
90	START	S1
10	START	S2

# This is a very, very, very simple grammar to get you started.

1	S1	NP VP .
1	S1	DO/DOES NP VP ?
1	S1	WDT DO/DOES NP VP ?

1	VP	VerbT NP
1	VP	VerbT Adj
1	VP	VBP

1	VBP	VB
1	VBP	VB Adj
1	VBP	VB NP VP
1	VBP	NP

1	DO/DOES	Do
1	DO/DOES	Does

20	NP	Det Nbar
1	NP	Proper
1	NP	Ving VNbar
1	NP	NNS
1	NP	PRP

1	VNbar	To Nbar

20	Nbar	Noun
1	Nbar	NNP
1	Nbar	Nbar PP

1	PP	Prep NP
